# -*- coding: utf-8 -*-
"""câu123btvnmodule2week2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TSSS3Y__1h5_q_tcDoSwsqU-bbglBhkc
"""

import numpy as np

def compute_vector_length(vector):
    return np.linalg.norm(vector)

def compute_dot_product(vector1, vector2):
    return np.dot(vector1, vector2)
def matrix_multi_vector(matrix, vector):
    return np.dot(matrix, vector)

def matrix_multi_matrix(matrix1, matrix2):
    return np.dot(matrix1, matrix2)

def inverse_matrix(matrix):
    return np.linalg.inv(matrix)
#Cho ma trận A = [[-2, 6], [8, -4]] Tính định thức của A:det(A) = (-2)(-4) - 6(8) = 8 - 48 = -40 Kiểm tra tính khả nghịch:det(A) ≠ 0, nên A có thể nghịch đảo Tính ma trận nghịch đảo:A^(-1) = (1/det(A)) * [[d, -b], [-c, a]]= (-1/40) * [[-4, -6], [-8, -2]]= [[1/10, 3/20], [1/5, 1/20]] Vậy A^(-1) = [[0.1, 0.15], [0.2, 0.05]]""

def compute_eigenvalues_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    # Normalize eigenvectors
    normalized_eigenvectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)
    return eigenvalues, normalized_eigenvectors
#Cho ma trận A = [[0.9, 0.2], [0.1, 0.8]]
# Tính định thức đặc trưng:
# det(A - λI) = (0.9 - λ)(0.8 - λ) - 0.02 = λ^2 - 1.7λ + 0.7 = 0
# Giải phương trình đặc trưng:
# λ^2 - 1.7λ + 0.7 = 0
#(λ - 1)(λ - 0.7) = 0
#λ1 = 1, λ2 = 0.7
#Tìm eigenvector cho λ1 = 1:
#(A - I)v = 0
#[[-0.1, 0.2], [0.1, -0.2]]v = 0
#v = [2, 1]
#Tìm eigenvector cho λ2 = 0.7:
#(A - 0.7I)v = 0
#[[0.2, 0.2], [0.1, 0.1]]v = 0
#v = [-1, 1]
#Chuẩn hóa các eigenvector:
#v1 = [2, 1] / sqrt(5) ≈ [0.8944, 0.4472]
#v2 = [-1, 1] / sqrt(2) ≈ [-0.7071, 0.7071]#

def compute_cosine(v1, v2):
    dot_product = np.dot(v1, v2)
    norm_v1 = np.linalg.norm(v1)
    norm_v2 = np.linalg.norm(v2)
    return dot_product / (norm_v1 * norm_v2)

#Cho x = [1, 2, 3, 4] và y = [1, 0, 3, 0]

#Tính tích vô hướng x·y:
#x·y = 11 + 20 + 33 + 40 = 10
#Tính độ dài của x:
#||x|| = sqrt(1^2 + 2^2 + 3^2 + 4^2) = sqrt(30) ≈ 5.4772
#Tính độ dài của y:
#||y|| = sqrt(1^2 + 0^2 + 3^2 + 0^2) = sqrt(10) ≈ 3.1623
#Tính cosine similarity:
#cs(x,y) = (x·y) / (||x|| * ||y||) = 10 / (5.4772 * 3.1623) ≈ 0.5773

#Vậy cosine similarity giữa x và y là khoảng 0.5773.

