# -*- coding: utf-8 -*-
"""btap2_module2_week1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19BODqccCS_RGj7ZUfNMieqVF64PPU5Qb
"""

import matplotlib.image as mpimg
import numpy as np

# Đọc ảnh
img = mpimg.imread('/content/dog.jpeg')

#Lightness method
gray_img_01 = (np.max(img, axis=2) + np.min(img, axis=2)) / 2

#Average method
gray_img_02 = np.mean(img, axis=2)

#Luminosity method

gray_img_03 = 0.21 * img[:,:,0] + 0.72 * img[:,:,1] + 0.07 * img[:,:,2]
# In giá trị pixel đầu tiên của ảnh xám
print(gray_img_01[0, 0])
print(gray_img_02[0, 0])
print(gray_img_03[0, 0])

!gdown iA0WmVfW88HyJvTBSQDI5vesf-pgKabq