# -*- coding: utf-8 -*-
"""pytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a257qJP75n_FJvIa16erWuW0CTzlUyVg
"""

# prompt: write softmax function using pytorch module

import torch
import torch.nn as nn

class Softmax(nn.Module):
    def __init__(self):
        super(Softmax, self).__init__()

    def forward(self, input):
        return torch.nn.functional.softmax(input, dim=1)