# -*- coding: utf-8 -*-
"""function đọc các câu trong một file txt,.ipynb

Automatically generated by Colab.

Original file is located ata
    https://colab.research.google.com/drive/1UnmO_K-4KtgUunZ9ctaN3uMgfuSXk60D
"""

'!gdown https://drive.google.com/uc?id=1IBScGdW2xlNsc9v5zSAya548kNgiOrko'
file_path = '/content/P1_data.txt'
txt = open(file_path, 'r')
data = txt.read().split()
dic = {i:data.count(i) for i in data}


print(dic)
txt.close()
