# -*- coding: utf-8 -*-
"""Module3-Week1-BTVN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Aw8ULD1eJ6MdWA6B4kA4OQioeEpHt3w
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv('/content/IMDB-Movie-Data.csv')
dataset.describe()
genre = dataset[['Genre']]

new_data = dataset[['Title','Genre','Actors','Director','Rating']]
new_data_1 = dataset.iloc[10:15][['Title','Rating','Revenue (Millions)']]

data= dataset[((dataset['Year']>=2010) & dataset['Year']<=2015)
              & (dataset['Rating']< 6)
              & (dataset['Revenue (Millions)']>dataset['Revenue (Millions)'].quantile(0.95))]
dataset.groupby('Director')[['Rating']].mean().head()
dataset.groupby('Director')[['Rating']].mean().sort_values(['Rating'], ascending = False).head()


dataset.isnull().sum()


dataset.drop('Metascore', axis =1,inplace = True)

dataset.head()

revenue_mean = dataset['Revenue (Millions)'].mean()
print ("The mean revenue is: ", revenue_mean )
dataset['Revenue (Millions)'].fillna(revenue_mean, inplace = True)

def rating_group(rating):
  if rating >= 7.5:
    return 'Good'
  elif rating >= 6 and rating < 7.5:
    return 'Average'
  else:
    return 'Bad'

dataset['Rating_category'] = dataset['Rating'].apply(rating_group)
dataset[['Title','Director','Rating','Rating_category']].head(5)

dataset_2 = pd.read_csv('/content/opsd_germany_daily.csv', index_col= 0, parse_dates = True)
dataset_2['Year'] = dataset_2.index.year
dataset_2['Month'] = dataset_2.index.month
dataset_2['Day'] = dataset_2.index.day_name()
dataset_2.sample( 5, random_state=0)
dataset_2.loc['2014-01-20':'2014-01-22']
dataset_2.loc['2012-02']

import seaborn as sns
sns.set(rc ={'figure.figsize':(11 , 4) })
dataset_2['Consumption'].plot(linewidth =0.5)
dataset_2_col = ['Consumption','Solar','Wind']
axes = dataset_2[dataset_2_col].plot(marker='.', alpha =0.5 , linestyle ='None',
figsize =(11,9),subplots = True )

for ax in axes :
  ax.set_ylabel('Daily Totals (GWh)')

plt.show()

fig,axes = plt.subplots(3 , 1 , figsize =(11 , 10) , sharex = True )
for name, ax in zip(['Consumption','Solar','Wind'],axes):
  sns.boxplot(data = dataset_2, x ='Month', y = name, ax = ax)
  ax.set_ylabel('GWh')
  ax.set_title(name)

  if ax!=axes[-1]:
    ax.set_xlabel('')

plt.show()

pd.date_range('1998 -03 -10','1998 -03 -15', freq ='D')

times_sample = pd. to_datetime (['2013 -02 -03','2013 -02 -06','2013 -02 -08'])

consum_sample = dataset_2.loc [ times_sample , ['Consumption']].copy()
consum_freq = consum_sample.asfreq ('D')

consum_freq ['Consumption - Forward Fill'] = consum_sample.asfreq('D', method ='ffill')
consum_freq

dataset_2_columns = ['Consumption','Wind','Solar','Wind+Solar']
dataset_2_weekly_mean = dataset_2[dataset_2_columns].resample("W").mean()
dataset_2_weekly_mean.head(3)

start, end = '2017-01', '2017-06'
# Plot daily and weekly resampled time series together
fig, ax = plt.subplots()
ax.plot( dataset_2.loc[start:end, 'Solar'],
marker='.', linestyle='-', linewidth=0.5, label='Daily')
ax.plot( dataset_2_weekly_mean.loc[start:end, 'Solar'],
 marker ='o', markersize =8 , linestyle ='-', label ='Weekly Mean Resample ')
ax.set_ylabel ('Solar Production (GWh )')
ax.legend ()
plt.show ()

opsd_annual = dataset_2[dataset_2_columns].resample('A').sum(min_count=360)  # Use 'A' for annual resampling
opsd_annual = opsd_annual.set_index(opsd_annual.index.year)
opsd_annual.index.name = 'Year'
# Compute the ratio of Wind + Solar to Consumption
opsd_annual['Wind + Solar / Consumption'] = opsd_annual['Wind+Solar'] / opsd_annual['Consumption']
opsd_annual.tail(3)

ax = opsd_annual.loc[2012:, 'Wind + Solar / Consumption'].plot.bar(color='C0') # Removed trailing space from column name
ax.set_ylabel('Fraction')
ax.set_ylim(0, 0.3)
ax.set_title('Wind + Solar Share of Annual Electricity Consumption')
plt.xticks(rotation =0)

opsd_7d = dataset_2[dataset_2_columns].rolling(7, center=True).mean()
opsd_7d.head(10)

import matplotlib.dates as mdates

# The min_periods =360 argument accounts for a few isolated missing days in the
# wind and solar production time series
opsd_365d = dataset_2[dataset_2_columns].rolling(window=365, center=True, min_periods=360).mean()
# Plot daily , 7 -day rolling mean , and 365 - day rolling mean time series
fig , ax = plt . subplots ()
ax.plot(dataset_2['Consumption'], marker='.', markersize=2, color='0.6',
 linestyle='None', label='Daily')
ax.plot(opsd_7d['Consumption'], linewidth=2, label='7-d Rolling Mean')
ax.plot(opsd_365d['Consumption'], color='0.2', linewidth=3,
label='Trend (365-d Rolling Mean)')
# Set x- ticks to yearly interval and add legend and labels
ax.xaxis.set_major_locator(mdates.YearLocator())
ax.legend()
ax.set_xlabel('Year')
ax.set_ylabel(' Consumption (GWh)')
ax.set_title('Trends in Electricity Consumption')
plt.show()

fig, ax = plt.subplots()
for nm in ['Wind', 'Solar', 'Wind+Solar']:
  ax.plot(opsd_365d[nm], label=nm)
  # Set x-ticks to yearly interval, adjust y-axis limits, add legend and labels
  ax.xaxis.set_major_locator(mdates.YearLocator())
  ax.set_ylim(0, 400)
  ax.legend()
  ax.set_ylabel('Production (GWh)')
  ax.set_title('Trends in Electricity Production (365 -d Rolling Means)')
  plt.show()

